FROM steepale/20190819_music2:1.1

WORKDIR /

# Only for local development
#RUN mkdir -p /Volumes/Frishman_4TB/bams_wgs_2014/normal
#    && mkdir -p /Volumes/Frishman_4TB/bams_wgs_2014/tumor
#COPY /Volumes/Frishman_4TB/bams_wgs_2014/normal /Volumes/Frishman_4TB/bams_wgs_2014/normal
#COPY /Volumes/Frishman_4TB/bams_wgs_2014/tumor /Volumes/Frishman_4TB/bams_wgs_2014/tumor

WORKDIR /

CMD ["/bin/bash"]
